[package]
name = "allrisbot"
version = "0.1.0"
edition = "2021"

[dependencies]
bb8-redis = "0.20.0"
env_logger = "0.11"
lazy_static = "1.5"
log = "0.4"
redis = { version = "0.28", default-features = false, features = ["keep-alive", "tokio-comp", "connection-manager", "script"] }
regex = "1"
reqwest = "0.12"
scraper = { version = "0.22", default-features = false }
serde = "1"
serde_json = "1.0"
serde-xml-rs = "0.6"
teloxide = { version = "0.13", features = ["macros", "throttle"] }
thiserror = "2"
tokio = { version = "1.39", features = ["rt", "macros", "rt-multi-thread", "sync"] }
url = "2.5"
clap = { version = "4.5.31", features = ["derive", "env"] }
