[package]
name = "allrisbot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std", "now", "serde"] }
env_logger = "0.11"
log = "0.4"
regex = "1"
reqwest = "0.12"
serde = "1"
serde-xml-rs = "0.6"
teloxide = { version = "0.13", features = ["macros"] }
thiserror="1"
tokio = { version = "1.39", features = ["rt", "macros", "rt-multi-thread", "sync"] }
