[package]
name = "allrisbot"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
env_logger = "0.11"
futures-util = "0.3"
lazy_static = "1.5"
log = "0.4"
redis = { version = "0.29", default-features = false, features = ["connection-manager", "keep-alive", "tokio-comp", "script", "json", "streams"] }
regex = "1"
reqwest = "0.12"
scraper = { version = "0.23", default-features = false }
serde = "1"
serde_json = "1.0"
serde-xml-rs = "0.6"
teloxide = { version = "0.13", features = ["macros"] }
thiserror = "2"
tokio = { version = "1.39", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-retry = "0.3"
url = "2.5"
rand = "0.9.0"

[features]
feed_from_file = []
