[package]
name = "allrisbot"
version = "0.1.0"
edition = "2021"

[features]
default = []
handle_updates = []

[dependencies]
env_logger = "0.11"
lazy_static = "1.5"
log = "0.4"
redis = { version = "0.27", default-features = false, features = ["keep-alive", "tokio-comp", "connection-manager"] }
regex = "1"
reqwest = "0.12"
scraper = { version = "0.20", default-features = false }
serde = "1"
serde-xml-rs = "0.6"
teloxide = { version = "0.13", features = ["macros", "throttle"] }
thiserror = "2"
tokio = { version = "1.43", features = ["rt", "macros", "rt-multi-thread", "sync"] }
url = "2.5"

[dev-dependencies]
serde_json = "1.0"
